### ISSUE TITLE
Badge Display Shortcodes

### ISSUE THREAD

**Issue by davelester** [davelester/WPBadgeDisplay#1]
Allows badges to be embedded in a theme by [shortcode](http://codex.wordpress.org/Shortcode_API). Would be great if all badges could be identified by a WordPress username, or an email address:

`[openbadges username="dave"] OR [openbadges email="dave@ischool.berkeley.edu"]`

It would also be nice if individual badges for a user could be embedded, using something like this:

`[openbadges username="dave" badge_name="Awesome Ninja"]`

**Comment by davelester** [comment]
This latter feature is tricky, because a badge name is actually a poor identifier. What if a user has been awarded multiple "awesome ninja" badges? The assertion url or evidence url is obviously ideal, but less convenient to type in or remember.

**Comment by davelester** [comment]
Shortcodes are working, embeddable using email address or username.

With commit e24a744, I added an hook for other plugins to add to shortcodes. Instead of anticipating all of the additional ways shortcodes can be used, I want the plugin to be extensible for other plugins like [WPBadger](https://github.com/davelester/WPBadger) which will allow badges locally installed to be referenced and displayed individually. 

Note: Despite closing this ticket, I suspect that other hooks may be necessary in the display widget to make it possible for plugins to control the display of badges.

**Comment by liquidgenius** [comment]
Is there a comprehensive list of the shortcodes available?

**Comment by davelester** [comment]
At this time, the shortcodes listed above are all that exists. If you'd like to add additional shortcodes, be my guest! Patches are welcome. :smile:
